version: '3'

services:
  webapp:
      container_name: webapp
      build: ./docker
      volumes:
        - './:/var/www/html'
      depends_on:
        - database
        - redis
      networks:
        - saloodo

  nginx:
      image: nginx
      container_name: nginx-server
      ports:
        - '8000:8000'
      volumes:
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - webapp
      networks:
        - saloodo

  redis:
      image: redis
      container_name: redis
      ports:
          - '6379:6379'
      entrypoint: redis-server --appendonly yes
      restart: always
      networks:
          - saloodo

  database:
      image: mysql:5.7
      container_name: mysql-database
      volumes:
          - db_data:/var/lib/mysql
      restart: always
      ports:
        - 3306
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: saloodo-store
      networks:
          - saloodo

networks:
    saloodo:
volumes:
    db_data:
